### ISSUE TITLE
Installations issue(s)

### ISSUE THREAD

**Issue by SteveClement** [CASES-LU/Fit4Cybersecurity#24]
Following the install path in the readme I fail on the following:

Not being a Django expert I am not sure what needs to be done. Setting STATIC_ROOT is not allowed.

```
(csskp-E_Z0xrL--py3.9) misp@misp-test:~/Fit4Cybersecurity$ python manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings.

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/home/misp/Fit4Cybersecurity/manage.py", line 21, in <module>
    main()
  File "/home/misp/Fit4Cybersecurity/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 338, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 248, in delete_file
    if self.storage.exists(prefixed_path):
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/core/files/storage.py", line 311, in exists
    return os.path.exists(self.path(name))
  File "/home/misp/.cache/pypoetry/virtualenvs/csskp-E_Z0xrL--py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 38, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```

**Comment by ruslanbaidan** [comment]
You need to modify csskp/settings.py uncomment the following [line](https://github.com/CASES-LU/Fit4Cybersecurity/blob/master/csskp/settings.py#L147), and comment [this one](https://github.com/CASES-LU/Fit4Cybersecurity/blob/master/csskp/settings.py#L150).
after the step of static collection is done, the lines state should be reverted ([1st commented](https://github.com/CASES-LU/Fit4Cybersecurity/blob/master/csskp/settings.py#L147), [2nd uncommented](https://github.com/CASES-LU/Fit4Cybersecurity/blob/master/csskp/settings.py#L150)).
